export {
  SignatureSchema,
  CreateSignatureSchema,
  type Signature,
  type CreateSignatureInput,
  SOCIAL_PLATFORMS,
  type SocialPlatform,
  SocialLinkSchema,
  type SocialLink,
  CustomLinkSchema,
  type CustomLink,
  COLOR_PRESETS,
  type ColorPresetId,
  LAYOUT_PRESETS,
  type LayoutPresetId,
  BrandingSchema,
  type Branding,
} from './signature.schema'
